export const siteConfig = {
  name: "Taller de Digitalización",
  seoTitle: "Informático para empresas y digitalización en Toledo | Taller de Digitalización",
  seoDescription:
    "Soporte informático, webs y digitalización para PyMEs en Toledo y a 50 km de Fuensalida. Presencial o en remoto, sin tecnicismos ni ventas innecesarias.",
  publicUrl: "https://tallerdedigitalizacion.com",
  bookingUrl: "https://calendly.com/tallerdedigitalizacion-info/30min",
  linktreeUrl: "https://linktr.ee/tallerdedigitalizacion",
  whatsappNumber: "34684768974",
  contactEmail: "info@tallerdedigitalizacion.com",
  phone: "+34632990133",
  phoneDisplay: "632 99 01 33",
  founder: "Pablo Leone",
  address: {
    streetAddress: "Numancia 4",
    postalCode: "45510",
    addressLocality: "Fuensalida",
    addressRegion: "Toledo",
    addressCountry: "ES",
  },
  geo: { latitude: 40.0497, longitude: -4.2038 },
  serviceRadiusKm: 50,
  serviceAreas: [
    "Fuensalida",
    "Torrijos",
    "Toledo",
    "Illescas",
    "Yuncos",
    "Seseña",
    "Bargas",
    "Olías del Rey",
    "Camarena",
    "Méntrida",
    "Escalona",
    "Santa Olalla",
    "Novés",
    "Valmojado",
    "Casarrubios del Monte",
    "Navalcarnero",
    "Móstoles",
    "Fuenlabrada",
    "Arroyomolinos",
    "Alcorcón",
    "Parla",
  ],
  googleBusinessUrl: "https://maps.app.goo.gl/iJYaupqoL8usLB6X7",
  githubUrl: "https://github.com/tallerdedigitalizacion",
  linkedinUrl: "https://www.linkedin.com/in/pabloleone/",
  googleAnalyticsId: "G-4GY58K423T",
  chatbaseId: "V8ryUqCVZxb4N8Hnym06s",
  ogImage: "/og-image.jpg",
  logo: "/logo.png",
  formEndpoint: "https://mbce6dz2wf.execute-api.eu-west-1.amazonaws.com/prod/",
  methodPdfPath: "/downloads/metodo-auditoria-caos-operativo.pdf",
};

export const whatsappUrl = `https://wa.me/${siteConfig.whatsappNumber}?text=Hola,%20vengo%20de%20la%20web%20de%20Taller%20de%20Digitalizaci%C3%B3n.%20Quer%C3%ADa%20consultar%20por%20el%20diagn%C3%B3stico%20operativo.`;
